### model
model_name_or_path: qwen1.5
reward_model: http://localhost:5000

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: Ideas
template: qwen
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/PPO
logging_steps: 1
save_steps: 10
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
reward_model_type: api

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
